# Generated by Django 3.1.3 on 2020-11-07 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 7, 17, 24, 2, 57641)),
        ),
    ]
