# Generated by Django 3.1.3 on 2020-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0004_auto_20201108_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
