# Generated by Django 3.1.3 on 2020-11-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0006_auto_20201114_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_id',
        ),
    ]
