# Generated by Django 3.1.3 on 2020-11-14 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0007_remove_message_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
