# Generated by Django 3.1.3 on 2020-11-14 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0008_message_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
