# Generated by Django 3.1.3 on 2020-11-14 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0009_auto_20201114_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
