# Generated by Django 3.1.3 on 2020-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0010_auto_20201114_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='year_in_school',
            field=models.CharField(choices=[('To be reviewed', 'To be reviewed'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='To be reviewed', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.CharField(max_length=50),
        ),
    ]
