# Generated by Django 3.1.3 on 2020-11-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0011_auto_20201114_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
