# Generated by Django 3.1.3 on 2020-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0012_auto_20201114_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_message',
            field=models.TextField(blank=True),
        ),
    ]
