# Generated by Django 3.1.3 on 2020-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0013_message_response_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
